extend type Booking {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Booking", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Booking` table.
  """
  _count: Int! @fdc_generated(from: "Booking.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Booking` table where the `checkInDate` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  checkInDate_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Booking.checkInDate", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Booking` table where the `checkOutDate` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  checkOutDate_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Booking.checkOutDate", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Booking` table where the `guestName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  guestName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Booking.guestName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Booking` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Booking.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Booking` table where the `propertyId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  propertyId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Booking.propertyId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Booking` table where the `roomId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  roomId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Booking.roomId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Booking` table where the `status` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  status_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Booking.status", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `checkInDate` field in the `Booking` table.
  """
  checkInDate_min: Date @fdc_generated(from: "Booking.checkInDate", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `checkOutDate` field in the `Booking` table.
  """
  checkOutDate_min: Date @fdc_generated(from: "Booking.checkOutDate", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `checkInDate` field in the `Booking` table.
  """
  checkInDate_max: Date @fdc_generated(from: "Booking.checkInDate", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `checkOutDate` field in the `Booking` table.
  """
  checkOutDate_max: Date @fdc_generated(from: "Booking.checkOutDate", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Booking.id", purpose: GLOBAL_ID)
}
extend type Property {
  """
  ✨ List `Booking` objects in a one-to-many relationship (where `Booking`.`property` is this object).
  """
  bookings_on_property(
    """
    Filter condition to narrow down the query results.
    """
    where: Booking_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Booking_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Booking_Having
  ): [Booking!]! @fdc_generated(from: "Booking.property", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Room` objects in a one-to-many relationship (where `Room`.`property` is this object).
  """
  rooms_on_property(
    """
    Filter condition to narrow down the query results.
    """
    where: Room_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Room_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Room_Having
  ): [Room!]! @fdc_generated(from: "Room.property", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `User` objects in a one-to-many relationship (where `User`.`property` is this object).
  """
  users_on_property(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User.property", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Property", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Property` table.
  """
  _count: Int! @fdc_generated(from: "Property.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Property` table where the `address` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  address_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Property.address", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Property` table where the `email` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  email_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Property.email", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Property` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Property.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Property` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Property.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Property` table where the `phoneNumber` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  phoneNumber_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Property.phoneNumber", purpose: QUERY_COUNT)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Property.id", purpose: GLOBAL_ID)
}
extend type Room {
  """
  ✨ List `Booking` objects in a one-to-many relationship (where `Booking`.`room` is this object).
  """
  bookings_on_room(
    """
    Filter condition to narrow down the query results.
    """
    where: Booking_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Booking_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Booking_Having
  ): [Booking!]! @fdc_generated(from: "Booking.room", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Room", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Room` table.
  """
  _count: Int! @fdc_generated(from: "Room.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Room` table where the `capacity` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  capacity_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Room.capacity", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Room` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Room.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Room` table where the `pricePerNight` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  pricePerNight_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Room.pricePerNight", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Room` table where the `propertyId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  propertyId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Room.propertyId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Room` table where the `roomNumber` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  roomNumber_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Room.roomNumber", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Room` table where the `roomType` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  roomType_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Room.roomType", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Room` table where the `status` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  status_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Room.status", purpose: QUERY_COUNT)
  """
  ✨ Sum the `capacity` field in the `Room` table.
  """
  capacity_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Room.capacity", purpose: QUERY_SUM)
  """
  ✨ Sum the `pricePerNight` field in the `Room` table.
  """
  pricePerNight_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Room.pricePerNight", purpose: QUERY_SUM)
  """
  ✨ Average the `capacity` field in the `Room` table.
  """
  capacity_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Room.capacity", purpose: QUERY_AVG)
  """
  ✨ Average the `pricePerNight` field in the `Room` table.
  """
  pricePerNight_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Room.pricePerNight", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `capacity` field in the `Room` table.
  """
  capacity_min: Int @fdc_generated(from: "Room.capacity", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `pricePerNight` field in the `Room` table.
  """
  pricePerNight_min: Float @fdc_generated(from: "Room.pricePerNight", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `capacity` field in the `Room` table.
  """
  capacity_max: Int @fdc_generated(from: "Room.capacity", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `pricePerNight` field in the `Room` table.
  """
  pricePerNight_max: Float @fdc_generated(from: "Room.pricePerNight", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Room.id", purpose: GLOBAL_ID)
}
extend type User {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "User", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `User` table.
  """
  _count: Int! @fdc_generated(from: "User.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `email` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  email_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.email", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `propertyId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  propertyId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.propertyId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `role` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  role_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.role", purpose: QUERY_COUNT)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "User.id", purpose: GLOBAL_ID)
}
